
name: CDNupdate-wd

on:
  workflow_dispatch:

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest
    
    steps:
    - name: kd
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}
      
    - name: cA
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Oq
      run: pip install requests

    - name: cr
      run: python bny.py

    - name: uc
      run: |
        git config --local user.email "ohhh@github.com"
        git config --local user.name "cdnF5er"
        git add data/
        if git diff-index --quiet HEAD --; then
          echo "No changes to commit"
        else
          git commit -m "cdn update $(date +'%Y-%m-%d %H:%M:%S') UTC"
          git push
        fi